#!/usr/bin/python2.7
# -*- coding: utf-8 -*-

"""
    Syncs shared portions of the kate docs to kwrite
    
    for illustration only
        might not run, definitely doesn't handle errors properly
"""

from __future__ import unicode_literals
import sys, os, codecs

#please fill in translations for your language here and commit to branches/work/doc
#or e-mail <tchollingsworth@gmail.com> and he'll add it for you
power_mode_translations = {
    "en": "(power user mode)"
    "es": "(el modo para usuarios avanzados)"
    ...
}

power_mode_comment = "<!--power mode in kwrite-->"

docs_to_sync = [
    "advanced.docbook",
    "part.docbook",
    ...
]

try:
    lang = sys.argv[1]
    kate_path = sys.argv[2]
    kwrite_path = sys.argv[3]
except IndexError:
    print "usage: sync.py <lang> <path to kate docs> <path to kwrite docs>"
    print "e.g.:  sync.py es ./kate ./kwrite"
    sys.exit(1)

try:
    power_mode_text = power_mode_translations[lang]
except IndexError:
    print "language '{0}' not found".format(lang)
    print "please add translation to top of sync.py"
    sys.exit(2)

for doc in docs_to_sync:
    kate_doc_path = os.path.join(kate_path, doc)
    kwrite_doc_path = os.path.join(kwrite_path, doc)

    with kate_fh = codecs.open(kate_doc_path, encoding='utf-8'):
        text = kate_fh.read().replace(power_mode_comment, power_mode_text)

        with kwrite_fh = codecs.open(kwrite_doc_path, 'w', encoding='utf-8'):
            kwrite_fh.write(text)