
OpenEmbedded nodistro.0 mx6ul-mzta-hmi ttyGS0

mx6ul-mzta-hmi login: root
root@mx6ul-mzta-hmi:~# journalctl -f
-- Logs begin at Fri 2018-05-11 10:08:58 UTC. --
May 11 11:18:03 mx6ul-mzta-hmi kernel: configfs-gadget gadget: acm ttyGS0 reqa1.                                                                             21 v0000 i0000 l7
May 11 11:18:03 mx6ul-mzta-hmi kernel: configfs-gadget gadget: acm ttyGS0 reqa1.                                                                             21 v0000 i0000 l7
May 11 11:18:03 mx6ul-mzta-hmi kernel: configfs-gadget gadget: acm ttyGS0 reqa1.                                                                             21 v0000 i0000 l7
May 11 11:18:03 mx6ul-mzta-hmi kernel: configfs-gadget gadget: acm ttyGS0 reqa1.                                                                             21 v0000 i0000 l7
May 11 11:18:03 mx6ul-mzta-hmi kernel: configfs-gadget gadget: acm ttyGS0 req21.                                                                             20 v0000 i0000 l7
May 11 11:18:03 mx6ul-mzta-hmi kernel: configfs-gadget gadget: acm ttyGS0 reqa1.                                                                             21 v0000 i0000 l7
May 11 11:18:03 mx6ul-mzta-hmi kernel: configfs-gadget gadget: acm ttyGS0 req21.                                                                             22 v0003 i0000 l0
May 11 11:18:03 mx6ul-mzta-hmi kernel: configfs-gadget gadget: acm ttyGS0 req21.                                                                             20 v0000 i0000 l7
May 11 11:18:03 mx6ul-mzta-hmi kernel: configfs-gadget gadget: acm ttyGS0 reqa1.                                                                             21 v0000 i0000 l7
May 11 11:18:15 mx6ul-mzta-hmi login[352]: ROOT LOGIN  on '/dev/ttyGS0'
May 11 11:18:50 mx6ul-mzta-hmi /usr/bin/k2d[375]: Opened file /tmp/k2/clients/conn_3/os_base.hex(32)
May 11 11:19:56 mx6ul-mzta-hmi algd[372]: Unload algorithm takes 252
May 11 11:19:56 mx6ul-mzta-hmi kontar2-gui.sh[369]: Alg updated
May 11 11:19:56 mx6ul-mzta-hmi /usr/bin/k2d[375]: [Errno 6] No such device or address
                                                  Traceback (most recent call last):
                                                    File "/usr/lib/python3.5/site-packages/kontar2/bus/device.py", line 517, in reset_modules
                                                      self.write_byte(self.BASE_MASTER_ADDRESS, I2C_BLOCK_BASIC_MODE, 0)
                                                    File "/usr/lib/python3.5/site-packages/kontar2/bus/device.py", line 509, in write_byte
                                                      self.dev.i2c_rdwr(msg)
                                                    File "/usr/lib/python3.5/site-packages/smbus2/smbus2.py", line 425, in i2c_rdwr
                                                      ioctl(self.fd, I2C_RDWR, ioctl_data)
                                                  OSError: [Errno 6] No such device or address
May 11 11:19:58 mx6ul-mzta-hmi /usr/bin/k2d[375]: Updating base module firmware with mb address 11
May 11 11:20:00 mx6ul-mzta-hmi /usr/bin/k2d[375]: Modbus write filed
                                                  Traceback (most recent call last):
                                                    File "/usr/lib/python3.5/site-packages/kontar2/bus/device.py", line 426, in _do_basic_write_file
                                                      await write_cb(req)
                                                    File "/usr/lib/python3.5/site-packages/kontar2/bus/device.py", line 450, in _mb_client_exec_throw
                                                      raise Exception('Modbus write filed')
                                                  Exception: Modbus write filed
May 11 11:20:00 mx6ul-mzta-hmi /usr/bin/k2d[375]: Modbus write filed
                                                  Traceback (most recent call last):
                                                    File "/usr/lib/python3.5/site-packages/kontar2/bus/device.py", line 426, in _do_basic_write_file
                                                      await write_cb(req)
                                                    File "/usr/lib/python3.5/site-packages/kontar2/bus/device.py", line 450, in _mb_client_exec_throw
                                                      raise Exception('Modbus write filed')
                                                  Exception: Modbus write filed
May 11 11:20:00 mx6ul-mzta-hmi /usr/bin/k2d[375]: [Errno 104] Connection reset by peer
                                                  NoneType: None
May 11 11:20:01 mx6ul-mzta-hmi /usr/bin/k2d[375]: Modbus write filed
                                                  Traceback (most recent call last):
                                                    File "/usr/lib/python3.5/site-packages/kontar2/bus/device.py", line 426, in _do_basic_write_file
                                                      await write_cb(req)
                                                    File "/usr/lib/python3.5/site-packages/kontar2/bus/device.py", line 450, in _mb_client_exec_throw
                                                      raise Exception('Modbus write filed')
                                                  Exception: Modbus write filed
May 11 11:20:01 mx6ul-mzta-hmi /usr/bin/k2d[375]: Modbus write filed
                                                  Traceback (most recent call last):
                                                    File "/usr/lib/python3.5/site-packages/kontar2/bus/device.py", line 426, in _do_basic_write_file
                                                      await write_cb(req)
                                                    File "/usr/lib/python3.5/site-packages/kontar2/bus/device.py", line 450, in _mb_client_exec_throw
                                                      raise Exception('Modbus write filed')
                                                  Exception: Modbus write filed
May 11 11:20:02 mx6ul-mzta-hmi /usr/bin/k2d[375]: Modbus write filed
                                                  Traceback (most recent call last):
                                                    File "/usr/lib/python3.5/site-packages/kontar2/bus/device.py", line 426, in _do_basic_write_file
                                                      await write_cb(req)
                                                    File "/usr/lib/python3.5/site-packages/kontar2/bus/device.py", line 450, in _mb_client_exec_throw
                                                      raise Exception('Modbus write filed')
                                                  Exception: Modbus write filed
May 11 11:20:02 mx6ul-mzta-hmi /usr/bin/k2d[375]: Modbus write filed
                                                  Traceback (most recent call last):
                                                    File "/usr/lib/python3.5/site-packages/kontar2/bus/device.py", line 426, in _do_basic_write_file
                                                      await write_cb(req)
                                                    File "/usr/lib/python3.5/site-packages/kontar2/bus/device.py", line 450, in _mb_client_exec_throw
                                                      raise Exception('Modbus write filed')
                                                  Exception: Modbus write filed
May 11 11:20:03 mx6ul-mzta-hmi /usr/bin/k2d[375]: Modbus write filed
                                                  Traceback (most recent call last):
                                                    File "/usr/lib/python3.5/site-packages/kontar2/bus/device.py", line 426, in _do_basic_write_file
                                                      await write_cb(req)
                                                    File "/usr/lib/python3.5/site-packages/kontar2/bus/device.py", line 450, in _mb_client_exec_throw
                                                      raise Exception('Modbus write filed')
                                                  Exception: Modbus write filed
May 11 11:20:03 mx6ul-mzta-hmi /usr/bin/k2d[375]: Modbus write filed
                                                  Traceback (most recent call last):
                                                    File "/usr/lib/python3.5/site-packages/kontar2/bus/device.py", line 426, in _do_basic_write_file
                                                      await write_cb(req)
                                                    File "/usr/lib/python3.5/site-packages/kontar2/bus/device.py", line 450, in _mb_client_exec_throw
                                                      raise Exception('Modbus write filed')
                                                  Exception: Modbus write filed
May 11 11:20:04 mx6ul-mzta-hmi /usr/bin/k2d[375]: Modbus write filed
                                                  Traceback (most recent call last):
                                                    File "/usr/lib/python3.5/site-packages/kontar2/bus/device.py", line 426, in _do_basic_write_file
                                                      await write_cb(req)
                                                    File "/usr/lib/python3.5/site-packages/kontar2/bus/device.py", line 450, in _mb_client_exec_throw
                                                      raise Exception('Modbus write filed')
                                                  Exception: Modbus write filed
May 11 11:20:04 mx6ul-mzta-hmi /usr/bin/k2d[375]: Modbus write filed
                                                  Traceback (most recent call last):
                                                    File "/usr/lib/python3.5/site-packages/kontar2/bus/device.py", line 426, in _do_basic_write_file
                                               