<?xml version="1.0" ?><root>
<report><version>2</version><sessionid>84daf6e2f7ceabbb5b63d07e</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2018-08-02 22:49:01</createtime><buildsignature>Local.Unknown.Unknown.1.45.62.1020-1.200.000.360.Release</buildsignature><categoryid>weather_service.py:1645</categoryid><desyncid>84daf6e2f7ceabbb5b63d07e</desyncid><systemconfig/><screenshot/><desyncdata>[manus] weather_service failed to handle zone load due to exception (AttributeError: type object 'WW_ooOLaLaWorld_Animations' has no attribute 'get')&#13;&#10;Traceback (most recent call last):&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 113, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 109, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 356, in c_api_client_connect&#13;&#10;  File ".\WickedWhims 3.3.4.129h\turbolib\injector_util.py", line 15, in _wrapped_function&#13;&#10;  File ".\WickedWhims 3.3.4.129h\turbolib\events\core.py", line 92, in _turbolib_on_late_zone_load&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 548, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1256, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 241, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 418, in on_zone_load&#13;&#10;  File ".\WickedWhims 3.3.4.129h\turbolib\injector_util.py", line 15, in _wrapped_function&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 415, in on_zone_load&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\weather\weather_service.py", line 1019, in on_zone_load&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\weather\weather_service.py", line 1042, in _send_new_weather_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\weather\weather_service.py", line 1705, in populate_forecasts&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\weather\weather_service.py", line 1645, in get_forecast&#13;&#10;AttributeError: type object 'WW_ooOLaLaWorld_Animations' has no attribute 'get'&#13;&#10;</desyncdata></report>
</root>