<div> 
Traceback (most recent call last):
  File "/home/ousmane/Documents/metsoMillRelineWebApp/backend/env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/ousmane/Documents/metsoMillRelineWebApp/backend/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/ousmane/Documents/metsoMillRelineWebApp/backend/env/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ousmane/Documents/metsoMillRelineWebApp/backend/env/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/ousmane/Documents/metsoMillRelineWebApp/backend/env/lib/python3.6/site-packages/rest_framework/viewsets.py", line 116, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ousmane/Documents/metsoMillRelineWebApp/backend/env/lib/python3.6/site-packages/rest_framework/views.py", line 495, in dispatch
    response = self.handle_exception(exc)
  File "/home/ousmane/Documents/metsoMillRelineWebApp/backend/env/lib/python3.6/site-packages/rest_framework/views.py", line 455, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/home/ousmane/Documents/metsoMillRelineWebApp/backend/env/lib/python3.6/site-packages/rest_framework/views.py", line 492, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/ousmane/Documents/metsoMillRelineWebApp/backend/env/lib/python3.6/site-packages/rest_framework/mixins.py", line 48, in list
    return Response(serializer.data)
  File "/home/ousmane/Documents/metsoMillRelineWebApp/backend/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 768, in data
    ret = super(ListSerializer, self).data
  File "/home/ousmane/Documents/metsoMillRelineWebApp/backend/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 262, in data
    self._data = self.to_representation(self.instance)
  File "/home/ousmane/Documents/metsoMillRelineWebApp/backend/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 686, in to_representation
    self.child.to_representation(item) for item in iterable
  File "/home/ousmane/Documents/metsoMillRelineWebApp/backend/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 686, in <listcomp>
    self.child.to_representation(item) for item in iterable
  File "/home/ousmane/Documents/metsoMillRelineWebApp/backend/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 530, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/home/ousmane/Documents/metsoMillRelineWebApp/backend/env/lib/python3.6/site-packages/rest_framework/serializers.py", line 686, in to_representation
    self.child.to_representation(item) for item in iterable
TypeError: 'Section' object is not iterable
[28/Feb/2019 16:06:52] "GET /api/ HTTP/1.1" 500 124819
</div>